//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallo_EF
{
    using System;
    
    public partial class Schuhgröße
    {
        public byte LinkerFuß { get; set; }
        public byte RechterFuß { get; set; }
    }
}
